name: Daily Scraper with Google Drive Upload

on:
  schedule:
    - cron: '0 6 * * *'  # každý den v 6:00 UTC
  workflow_dispatch:

jobs:
  scrape-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Save Google Credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: echo "$GOOGLE_CREDENTIALS" > credentials.json

    - name: Run scraper and upload
      run: |
        python Strankovani_python.py
        python upload_to_drive.py
